### ISSUE TITLE
query regarding more symptoms 

### ISSUE THREAD

**Issue by ikalpeshjoshi** [tmsreekanth98/Medical_Symptom_Analyser#1]
can you tell me how do i add more symptoms ??

**Comment by tmsreekanth98** [comment]
Symptoms depend on API Medic API's. Currently the Sandbox version is being used as this is just a prototype. The paid version of the API contains more symptoms and corresponding data. To incorporate paid version, just change the API key to the premium one and change API Endpoint wherever used in views.py file.
