### ISSUE TITLE
Choosing more than 1 symptom

### ISSUE THREAD

**Issue by mcmclarry** [tmsreekanth98/Medical_Symptom_Analyser#2]
Hi. Is it possible to choose more than one symptom on the list and generate a treatment based from those selection?

**Comment by KriAga** [comment]
Refer Here: https://github.com/tmsreekanth98/Medical_Symptom_Analyser/issues/1#issuecomment-527020032

**Comment by mcmclarry** [comment]
So it's not possible to select 2 or more symptom at once?

**Comment by KriAga** [comment]
Comma-separated symptom ids will fetch you the result

![image](https://user-images.githubusercontent.com/20995709/73750964-25950600-4784-11ea-83fb-e7b4ff087164.png)

**Comment by tmsreekanth98** [comment]
> Comma-separated symptom ids will fetch you the result
> 
> ![image](https://user-images.githubusercontent.com/20995709/73750964-25950600-4784-11ea-83fb-e7b4ff087164.png)

Its been some time since I have worked on this project. Can you try if the comma separated method works? The API itself is designed to get multiple symptom results in one go, but I am not sure whether the django application is built to handle it. You are free to modify it and add this feature if you wish.

**Comment by KriAga** [comment]
The last time I checked it, it was working. The API accepts an array of symptom IDs. I had checked that in a flask application. I think there is no change in that, nevertheless, one can always check and confirm this.

**Comment by KriAga** [comment]
I think you can close this issue.

**Comment by tmsreekanth98** [comment]
Closing this issue.
